# Generated by Django 4.2.2 on 2023-06-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_lot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='startTime',
            new_name='start_time',
        ),
    ]
