# Generated by Django 4.2.2 on 2023-06-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_alter_auction_owner_alter_auction_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='auction',
            new_name='auction_id',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
