# Generated by Django 4.2.2 on 2023-06-22 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0011_alter_auction_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='winner_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots_as_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lot',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots_as_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
