# Generated by Django 4.2.2 on 2023-06-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_lot_winner_id_alter_lot_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
