# Generated by Django 4.2.2 on 2023-06-25 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_auction_description_alter_lot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
