# Generated by Django 4.2.2 on 2023-06-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_auction_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
