# Generated by Django 4.2.2 on 2023-06-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_alter_bid_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('lot_id',)},
        ),
    ]
