# Generated by Django 4.2.2 on 2023-06-27 09:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0017_alter_bid_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('owner_id', 'lot_id')},
        ),
    ]
